# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  displayName: 'Terraform install'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV4@4
  displayName: 'Terraform init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'AMBIKA VS(20bac492-273c-4d6e-81a6-c451996ee342)'
    backendAzureRmResourceGroupName: 'storage001'
    backendAzureRmStorageAccountName: 'stg22111'
    backendAzureRmContainerName: 'stss'
    backendAzureRmKey: 'apim.tfstate'

- task: TerraformTaskV4@4
  displayName: 'Validate terraform'
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'AMBIKA VS(20bac492-273c-4d6e-81a6-c451996ee342)'

- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'AMBIKA VS(20bac492-273c-4d6e-81a6-c451996ee342)'
